
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  English: {
    langCode: "EN", home: "Home", research: "Research", library: "Library",
    folderMgmt: "Folders", trash: "Trash", adminPanel: "Admin Panel",
    welcome: "Welcome", login: "Login", logout: "Logout",
    approve: "Approve", reject: "Reject", status: "Status",
    pending: "Pending", approved: "Approved",
    userMgmt: "User Management", searchPlaceholder: "Ask anything about your documents...",
    brandName: "DocuMind", portalName: "Intel Portal",
    history: "History", download: "Download", delete: "Delete",
    createFolder: "New Folder", uploadFile: "Upload File",
    back: "Back", emptyFolder: "This folder is empty",
    folderNamePlaceholder: "Enter folder name...",
    startNew: "New Conversation", recentDiscussions: "Recent",
    knowledgeTitle: "Knowledge Base", uploadDesc: "Upload",
    noDocsFocused: "No documents selected for this session", docDetails: "Details",
    restore: "Restore", modeLibrary: "Global Library", modeFocus: "Session Files",
    selectMode: "Mode", focusNewDocs: "Upload Files",
    focusDesc: "Chat with specific documents",
    useLibrary: "Library", libraryDesc: "Search all approved data",
    summaryPrompt: "Summarize the key findings.",
    rawContent: "Source Content", focusedDocs: "Context Files",
    uploadSuccess: "Uploaded!",
    folderSuccess: "Folder created!",
    activityTitle: "Activity Log", selectFolderChat: "Context:",
    allFolders: "Full Library",
    slogan: "Your Knowledge, Amplified by Intelligence.",
    uploading: "Processing files...",
    selectToChat: "Select files to include in conversation",
    personalFolder: "Personal",
    departments: "Departments",
    addUser: "Create User",
    deptManagement: "Org Structure",
    noDept: "Public / No Dept",
    selectDept: "Select Department",
    orgChart: "Organization",
    createDept: "Create Department",
    employee: "EMPLOYEE",
    adminRole: "ADMIN",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Security password",
    loginAction: "ENTER SYSTEM",
    loginError: "Invalid credentials.",
    securityNote: "DocuMind AI Security",
    lightMode: "Light",
    darkMode: "Dark",
    systemMode: "Web",
    orgStructure: "Org Structure",
    members: "Members",
    mainStorage: "Main Storage",
    backBtn: "Back",
    confirmDelete: "Permanently delete this item?",
    noDiscussions: "No discussions yet",
    profile: "Profile",
    activityLogDesc: "Full history of activities",
    processing: "Processing...",
    askAiFolder: "Ask AI about this folder",
    noActivities: "No activities recorded yet",
    basicInfo: "Basic Information",
    systemPermissions: "System Permissions",
    accessKnowledge: "Access Knowledge",
    accessKnowledgeDesc: "Full access to department docs",
    adminDashboardDesc: "Manage users and org structure",
    protectedByAi: "Account protected by AI Intelligence",
    personalStorage: "Personal Storage",
    newDept: "New Department",
    deptNamePlaceholder: "Department name...",
    saveStructure: "Save Structure",
    newFolder: "New Folder",
    folderName: "Folder Name",
    cancel: "Cancel",
    create: "Create",
    identifyEmail: "Identify Email",
    authAccount: "Authorize Account",
    userDirectory: "User Directory",
    namePlaceholder: "Full Name"
  },
  Vietnamese: {
    langCode: "VN", home: "Trang chủ", research: "Nghiên cứu", library: "Thư viện",
    folderMgmt: "Thư mục", trash: "Thùng rác", adminPanel: "Quản trị",
    welcome: "Chào mừng", login: "Đăng nhập", logout: "Đăng xuất",
    approve: "Duyệt", reject: "Từ chối", status: "Trạng thái",
    pending: "Chờ duyệt", approved: "Đã duyệt",
    userMgmt: "Quản lý User", searchPlaceholder: "Hỏi bất cứ điều gì về tài liệu của bạn...",
    brandName: "DocuMind", portalName: "Cổng thông tin",
    history: "Lịch sử", download: "Tải về", delete: "Xóa",
    createFolder: "Thư mục mới", uploadFile: "Tải file lên",
    back: "Quay lại", emptyFolder: "Thư mục này trống",
    folderNamePlaceholder: "Nhập tên thư mục...",
    startNew: "Cuộc trò chuyện", recentDiscussions: "Thảo luận gần đây",
    knowledgeTitle: "Kho tri thức", uploadDesc: "Tải lên",
    noDocsFocused: "Chưa có tài liệu nào được chọn cho phiên này", docDetails: "Chi tiết tài liệu",
    restore: "Khôi phục", modeLibrary: "Thư viện chung", modeFocus: "Tệp tải lên",
    selectMode: "Chế độ", focusNewDocs: "Tải tệp lên",
    focusDesc: "Trò chuyện với tài liệu cụ thể",
    useLibrary: "Dùng thư viện", libraryDesc: "Tìm kiếm toàn bộ kho",
    summaryPrompt: "Tóm tắt các ý chính.",
    rawContent: "Nội dung gốc", focusedDocs: "Tệp ngữ cảnh",
    uploadSuccess: "Đã tải lên!",
    folderSuccess: "Đã tạo thư mục!",
    activityTitle: "Lịch sử hoạt động", selectFolderChat: "Ngữ cảnh:",
    allFolders: "Toàn bộ thư viện",
    slogan: "Tri thức của bạn, Sức mạnh của chúng tôi.",
    uploading: "Đang xử lý tài liệu...",
    selectToChat: "Chọn tài liệu để bắt đầu trò chuyện",
    personalFolder: "Cá nhân",
    departments: "Phòng ban",
    addUser: "Tạo User",
    deptManagement: "Cơ cấu tổ chức",
    noDept: "Công khai / Không PB",
    selectDept: "Chọn phòng ban",
    orgChart: "Sơ đồ tổ chức",
    createDept: "Tạo phòng ban",
    employee: "NHÂN VIÊN",
    adminRole: "QUẢN TRỊ",
    emailPlaceholder: "Email định danh",
    passwordPlaceholder: "Mật khẩu bảo mật",
    loginAction: "VÀO HỆ THỐNG",
    loginError: "Thông tin xác thực không chính xác.",
    securityNote: "Bảo mật bởi DocuMind AI",
    lightMode: "Sáng",
    darkMode: "Tối",
    systemMode: "Web",
    orgStructure: "Cơ cấu tổ chức",
    members: "Thành viên",
    mainStorage: "Kho lưu trữ chính",
    backBtn: "Quay lại",
    confirmDelete: "Bạn có chắc chắn muốn xóa vĩnh viễn?",
    noDiscussions: "Chưa có thảo luận nào",
    profile: "Hồ sơ",
    activityLogDesc: "Toàn bộ lịch sử hoạt động",
    processing: "Đang xử lý...",
    askAiFolder: "Hỏi AI về thư mục",
    noActivities: "Chưa có hoạt động nào được ghi lại",
    basicInfo: "Thông tin cơ bản",
    systemPermissions: "Quyền hạn hệ thống",
    accessKnowledge: "Truy cập tri thức",
    accessKnowledgeDesc: "Toàn quyền xem tài liệu phòng ban",
    adminDashboardDesc: "Quản lý User & Cấu trúc tổ chức",
    protectedByAi: "Tài khoản đã được bảo vệ bởi AI",
    personalStorage: "Cá nhân",
    newDept: "Phòng ban mới",
    deptNamePlaceholder: "Tên phòng ban...",
    saveStructure: "Lưu cấu trúc",
    newFolder: "Thư mục mới",
    folderName: "Tên thư mục",
    cancel: "Hủy",
    create: "Tạo",
    identifyEmail: "Email định danh",
    authAccount: "Xác thực tài khoản",
    userDirectory: "Danh bạ nhân sự",
    namePlaceholder: "Họ và tên"
  },
  French: {
    langCode: "FR", home: "Accueil", research: "Recherche", library: "Bibliothèque",
    folderMgmt: "Dossiers", trash: "Corbeille", adminPanel: "Admin",
    welcome: "Bienvenue", login: "Connexion", logout: "Déconnexion",
    approve: "Approuver", reject: "Rejeter", status: "Statut",
    pending: "En attente", approved: "Approuvé",
    userMgmt: "Gestion Utilisateurs", searchPlaceholder: "Posez une question...",
    brandName: "DocuMind", portalName: "Portail Intel",
    history: "Historique", download: "Télécharger", delete: "Supprimer",
    createFolder: "Nouveau Dossier", uploadFile: "Téléverser",
    back: "Retour", emptyFolder: "Ce dossier est vide",
    folderNamePlaceholder: "Nom du dossier...",
    startNew: "Nouvelle Discussion", recentDiscussions: "Récent",
    knowledgeTitle: "Base de Connaissances", uploadDesc: "Téléverser",
    noDocsFocused: "Aucun document sélectionné", docDetails: "Détails",
    restore: "Restaurer", modeLibrary: "Bibliothèque Globale", modeFocus: "Fichiers de Session",
    selectMode: "Mode", focusNewDocs: "Téléverser Fichiers",
    focusDesc: "Discuter avec des documents",
    useLibrary: "Bibliothèque", libraryDesc: "Rechercher partout",
    summaryPrompt: "Résumer les points clés.",
    rawContent: "Source", focusedDocs: "Fichiers Contexte",
    uploadSuccess: "Téléversé !",
    folderSuccess: "Dossier créé !",
    activityTitle: "Activités", selectFolderChat: "Contexte:",
    allFolders: "Bibliothèque Complète",
    slogan: "Votre Savoir, Amplifié.",
    uploading: "Traitement...",
    selectToChat: "Sélectionner les fichiers",
    personalFolder: "Personnel",
    departments: "Départements",
    addUser: "Créer Utilisateur",
    deptManagement: "Structure",
    noDept: "Public / Aucun",
    selectDept: "Choisir Département",
    orgChart: "Organisation",
    createDept: "Créer Département",
    employee: "EMPLOYÉ",
    adminRole: "ADMIN",
    emailPlaceholder: "Adresse email",
    passwordPlaceholder: "Mot de passe",
    loginAction: "ENTRER",
    loginError: "Identifiants invalides.",
    securityNote: "Sécurité DocuMind AI",
    lightMode: "Clair",
    darkMode: "Sombre",
    systemMode: "Web",
    orgStructure: "Structure Org",
    members: "Membres",
    mainStorage: "Stockage Principal",
    backBtn: "Retour",
    confirmDelete: "Supprimer définitivement ?",
    noDiscussions: "Pas encore de discussions",
    profile: "Profil",
    activityLogDesc: "Historique complet",
    processing: "Traitement...",
    askAiFolder: "Demander à l'IA",
    noActivities: "Aucune activité",
    basicInfo: "Informations de Base",
    systemPermissions: "Permissions Système",
    accessKnowledge: "Accès Savoir",
    accessKnowledgeDesc: "Accès complet aux documents",
    adminDashboardDesc: "Gérer les utilisateurs",
    protectedByAi: "Protégé par IA",
    personalStorage: "Personnel",
    newDept: "Nouveau Dépt",
    deptNamePlaceholder: "Nom du dépt...",
    saveStructure: "Enregistrer",
    newFolder: "Dossier",
    folderName: "Nom",
    cancel: "Annuler",
    create: "Créer",
    identifyEmail: "Email d'identification",
    authAccount: "Autoriser",
    userDirectory: "Annuaire",
    namePlaceholder: "Nom Complet"
  },
  German: {
    langCode: "DE", home: "Startseite", research: "Forschung", library: "Bibliothek",
    folderMgmt: "Ordner", trash: "Papierkorb", adminPanel: "Admin",
    welcome: "Willkommen", login: "Anmelden", logout: "Abmelden",
    approve: "Genehmigen", reject: "Ablehnen", status: "Status",
    pending: "Ausstehend", approved: "Genehmigt",
    userMgmt: "Benutzerverwaltung", searchPlaceholder: "Fragen Sie etwas...",
    brandName: "DocuMind", portalName: "Intel Portal",
    history: "Verlauf", download: "Herunterladen", delete: "Löschen",
    createFolder: "Neuer Ordner", uploadFile: "Hochladen",
    back: "Zurück", emptyFolder: "Dieser Ordner ist leer",
    folderNamePlaceholder: "Ordnername...",
    startNew: "Neues Gespräch", recentDiscussions: "Zuletzt",
    knowledgeTitle: "Wissensdatenbank", uploadDesc: "Hochladen",
    noDocsFocused: "Keine Dokumente ausgewählt", docDetails: "Details",
    restore: "Wiederherstellen", modeLibrary: "Globale Bibliothek", modeFocus: "Sitzungsdateien",
    selectMode: "Modus", focusNewDocs: "Hochladen",
    focusDesc: "Mit Dokumenten chatten",
    useLibrary: "Bibliothek", libraryDesc: "Alle Daten durchsuchen",
    summaryPrompt: "Zusammenfassung erstellen.",
    rawContent: "Inhalt", focusedDocs: "Kontextdateien",
    uploadSuccess: "Hochgeladen!",
    folderSuccess: "Ordner erstellt!",
    activityTitle: "Aktivitätsprotokoll", selectFolderChat: "Kontext:",
    allFolders: "Vollständige Bibliothek",
    slogan: "Ihr Wissen, Intelligent Erweitert.",
    uploading: "Wird verarbeitet...",
    selectToChat: "Dateien auswählen",
    personalFolder: "Persönlich",
    departments: "Abteilungen",
    addUser: "Benutzer erstellen",
    deptManagement: "Struktur",
    noDept: "Öffentlich / Keine",
    selectDept: "Abteilung wählen",
    orgChart: "Organisation",
    createDept: "Abteilung erstellen",
    employee: "MITARBEITER",
    adminRole: "ADMIN",
    emailPlaceholder: "E-Mail-Adresse",
    passwordPlaceholder: "Passwort",
    loginAction: "SYSTEM BETRETEN",
    loginError: "Ungültige Anmeldedaten.",
    securityNote: "DocuMind AI Sicherheit",
    lightMode: "Hell",
    darkMode: "Dunkel",
    systemMode: "Web",
    orgStructure: "Org-Struktur",
    members: "Mitglieder",
    mainStorage: "Hauptspeicher",
    backBtn: "Zurück",
    confirmDelete: "Endgültig löschen?",
    noDiscussions: "Noch keine Gespräche",
    profile: "Profil",
    activityLogDesc: "Gesamter Verlauf",
    processing: "Wird verarbeitet...",
    askAiFolder: "KI fragen",
    noActivities: "Keine Aktivitäten",
    basicInfo: "Basisinfo",
    systemPermissions: "Berechtigungen",
    accessKnowledge: "Wissenszugriff",
    accessKnowledgeDesc: "Vollzugriff auf Dok",
    adminDashboardDesc: "Benutzer verwalten",
    protectedByAi: "KI-geschützt",
    personalStorage: "Persönlich",
    newDept: "Neue Abteilung",
    deptNamePlaceholder: "Name...",
    saveStructure: "Speichern",
    newFolder: "Ordner",
    folderName: "Ordnername",
    cancel: "Abbrechen",
    create: "Erstellen",
    identifyEmail: "E-Mail",
    authAccount: "Autorisieren",
    userDirectory: "Verzeichnis",
    namePlaceholder: "Vollständiger Name"
  },
  Japanese: {
    langCode: "JP", home: "ホーム", research: "研究", library: "ライブラリ",
    folderMgmt: "フォルダ", trash: "ゴミ箱", adminPanel: "管理者",
    welcome: "ようこそ", login: "ログイン", logout: "ログアウト",
    approve: "承認", reject: "拒否", status: "状態",
    pending: "保留中", approved: "承認済み",
    userMgmt: "ユーザー管理", searchPlaceholder: "ドキュメントについて質問する...",
    brandName: "DocuMind", portalName: "インテルポータル",
    history: "履歴", download: "ダウンロード", delete: "削除",
    createFolder: "新規フォルダ", uploadFile: "アップロード",
    back: "戻る", emptyFolder: "フォルダは空です",
    folderNamePlaceholder: "フォルダ名...",
    startNew: "新しい会話", recentDiscussions: "最近",
    knowledgeTitle: "知識ベース", uploadDesc: "アップロード",
    noDocsFocused: "ドキュメントが選択されていません", docDetails: "詳細",
    restore: "元に戻す", modeLibrary: "グローバルライブラリ", modeFocus: "セッションファイル",
    selectMode: "モード", focusNewDocs: "ファイルをアップ",
    focusDesc: "ドキュメントと対話",
    useLibrary: "ライブラリ", libraryDesc: "全データを検索",
    summaryPrompt: "主要な要点を要約して。",
    rawContent: "ソース", focusedDocs: "コンテキスト",
    uploadSuccess: "完了！",
    folderSuccess: "フォルダ作成！",
    activityTitle: "アクティビティログ", selectFolderChat: "コンテキスト:",
    allFolders: "全ライブラリ",
    slogan: "あなたの知識を、知能で強化する。",
    uploading: "処理中...",
    selectToChat: "ファイルを選択",
    personalFolder: "個人用",
    departments: "部署",
    addUser: "ユーザー作成",
    deptManagement: "組織構造",
    noDept: "公開 / 部署なし",
    selectDept: "部署を選択",
    orgChart: "組織図",
    createDept: "部署作成",
    employee: "従業員",
    adminRole: "管理者",
    emailPlaceholder: "メールアドレス",
    passwordPlaceholder: "Passwort",
    loginAction: "システムに入る",
    loginError: "ログイン情報が正しくありません。",
    securityNote: "DocuMind AI セキュリティ",
    lightMode: "ライト",
    darkMode: "ダーク",
    systemMode: "Web",
    orgStructure: "組織構造",
    members: "メンバー",
    mainStorage: "メインストレージ",
    backBtn: "戻る",
    confirmDelete: "完全に削除しますか？",
    noDiscussions: "会話はまだありません",
    profile: "プロフィール",
    activityLogDesc: "全履歴",
    processing: "処理中...",
    askAiFolder: "AIに聞く",
    noActivities: "記録はありません",
    basicInfo: "基本情報",
    systemPermissions: "システム権限",
    accessKnowledge: "知識アクセス",
    accessKnowledgeDesc: "ドキュメントへの全アクセス",
    adminDashboardDesc: "ユーザーと組織を管理",
    protectedByAi: "AIで保護されています",
    personalStorage: "個人用",
    newDept: "新しい部署",
    deptNamePlaceholder: "部署名...",
    saveStructure: "構造を保存",
    newFolder: "新規フォルダ",
    folderName: "名前",
    cancel: "キャンセル",
    create: "作成",
    identifyEmail: "識別メール",
    authAccount: "アカウント認証",
    userDirectory: "ユーザー名簿",
    namePlaceholder: "氏名"
  },
  Korean: {
    langCode: "KR", home: "홈", research: "연구", library: "라이브러리",
    folderMgmt: "폴더", trash: "휴지통", adminPanel: "관리자",
    welcome: "환영합니다", login: "로그인", logout: "로그아웃",
    approve: "승인", reject: "거절", status: "상태",
    pending: "대기 중", approved: "승인됨",
    userMgmt: "사용자 관리", searchPlaceholder: "무엇이든 물어보세요...",
    brandName: "DocuMind", portalName: "인텔 포털",
    history: "기록", download: "다운로드", delete: "삭제",
    createFolder: "새 폴더", uploadFile: "업로드",
    back: "뒤로", emptyFolder: "폴더가 비어 있습니다",
    folderNamePlaceholder: "폴더 이름...",
    startNew: "새 대화", recentDiscussions: "최근",
    knowledgeTitle: "지식 베이스", uploadDesc: "업로드",
    noDocsFocused: "선택된 문서 없음", docDetails: "상세 정보",
    restore: "복구", modeLibrary: "전체 라이브러리", modeFocus: "세션 파일",
    selectMode: "모드", focusNewDocs: "파일 업로드",
    focusDesc: "문서와 대화하기",
    useLibrary: "라이브러리", libraryDesc: "모든 데이터 검색",
    summaryPrompt: "주요 내용을 요약해줘.",
    rawContent: "소스", focusedDocs: "컨텍스트 파일",
    uploadSuccess: "업로드 완료!",
    folderSuccess: "폴더 생성 완료!",
    activityTitle: "활동 로그", selectFolderChat: "컨텍스트:",
    allFolders: "전체 라이브러리",
    slogan: "당신의 지식, 지능으로 증폭되다.",
    uploading: "처리 중...",
    selectToChat: "파일 선택",
    personalFolder: "개인",
    departments: "부서",
    addUser: "사용자 생성",
    deptManagement: "조직 구조",
    noDept: "공개 / 부서 없음",
    selectDept: "부서 선택",
    orgChart: "조직도",
    createDept: "부서 생성",
    employee: "직원",
    adminRole: "관리자",
    emailPlaceholder: "이메일 주소",
    passwordPlaceholder: "비밀번호",
    loginAction: "시스템 접속",
    loginError: "잘못된 정보입니다.",
    securityNote: "DocuMind AI 보안",
    lightMode: "라이트",
    darkMode: "다크",
    systemMode: "Web",
    orgStructure: "조직 구조",
    members: "멤버",
    mainStorage: "메인 저장소",
    backBtn: "뒤로",
    confirmDelete: "영구적으로 삭제하시겠습니까?",
    noDiscussions: "대화 기록 없음",
    profile: "프로필",
    activityLogDesc: "전체 활동 기록",
    processing: "처리 중...",
    askAiFolder: "AI에게 묻기",
    noActivities: "활동 기록 없음",
    basicInfo: "기본 정보",
    systemPermissions: "시스템 권한",
    accessKnowledge: "지식 액세스",
    accessKnowledgeDesc: "부서 문서 전체 액세스",
    adminDashboardDesc: "사용자 및 조직 관리",
    protectedByAi: "AI로 보호됨",
    personalStorage: "개인 저장소",
    newDept: "새 부서",
    deptNamePlaceholder: "부서명...",
    saveStructure: "구조 저장",
    newFolder: "새 폴더",
    folderName: "폴더명",
    cancel: "취소",
    create: "생성",
    identifyEmail: "이메일 확인",
    authAccount: "계정 인증",
    userDirectory: "사용자 디렉토리",
    namePlaceholder: "성명"
  },
  Chinese: {
    langCode: "CN", home: "首页", research: "研究", library: "知识库",
    folderMgmt: "文件夹", trash: "回收站", adminPanel: "管理后台",
    welcome: "欢迎", login: "登录", logout: "登出",
    approve: "批准", reject: "拒绝", status: "状态",
    pending: "待处理", approved: "已批准",
    userMgmt: "用户管理", searchPlaceholder: "询问任何关于文档的问题...",
    brandName: "DocuMind", portalName: "信息门户",
    history: "历史记录", download: "下载", delete: "删除",
    createFolder: "新建文件夹", uploadFile: "上传文件",
    back: "返回", emptyFolder: "文件夹为空",
    folderNamePlaceholder: "输入文件夹名称...",
    startNew: "开启新对话", recentDiscussions: "最近对话",
    knowledgeTitle: "知识库", uploadDesc: "上传",
    noDocsFocused: "未选择任何文档", docDetails: "文档详情",
    restore: "恢复", modeLibrary: "全局库", modeFocus: "会话文件",
    selectMode: "模式", focusNewDocs: "上传文件",
    focusDesc: "与特定文档对话",
    useLibrary: "知识库", libraryDesc: "搜索所有已批准数据",
    summaryPrompt: "总结主要发现。",
    rawContent: "原文内容", focusedDocs: "上下文文件",
    uploadSuccess: "上传成功！",
    folderSuccess: "文件夹已创建！",
    activityTitle: "活动日志", selectFolderChat: "上下文:",
    allFolders: "完整库",
    slogan: "您的知识，由智能赋能。",
    uploading: "正在处理...",
    selectToChat: "选择文件加入对话",
    personalFolder: "个人",
    departments: "部门",
    addUser: "创建用户",
    deptManagement: "组织结构",
    noDept: "公开 / 无部门",
    selectDept: "选择部门",
    orgChart: "组织架构",
    createDept: "创建部门",
    employee: "员工",
    adminRole: "管理员",
    emailPlaceholder: "电子邮箱",
    passwordPlaceholder: "安全密码",
    loginAction: "进入系统",
    loginError: "登录信息无效。",
    securityNote: "DocuMind AI 安全防护",
    lightMode: "浅色",
    darkMode: "深色",
    systemMode: "自动",
    orgStructure: "组织结构",
    members: "成员",
    mainStorage: "主存储",
    backBtn: "返回",
    confirmDelete: "永久删除此项？",
    noDiscussions: "暂无对话",
    profile: "个人资料",
    activityLogDesc: "完整活动历史",
    processing: "处理中...",
    askAiFolder: "关于此文件夹询问AI",
    noActivities: "暂无记录",
    basicInfo: "基本信息",
    systemPermissions: "系统权限",
    accessKnowledge: "知识访问",
    accessKnowledgeDesc: "完整访问部门文档",
    adminDashboardDesc: "管理用户和架构",
    protectedByAi: "账号受AI保护",
    personalStorage: "个人存储",
    newDept: "新部门",
    deptNamePlaceholder: "部门名称...",
    saveStructure: "保存结构",
    newFolder: "新文件夹",
    folderName: "文件夹名称",
    cancel: "取消",
    create: "创建",
    identifyEmail: "识别邮箱",
    authAccount: "授权账号",
    userDirectory: "人员名单",
    namePlaceholder: "姓名"
  }
};
