
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  English: {
    langCode: "EN", home: "Home", research: "Research", library: "Library",
    folderMgmt: "Folders", trash: "Trash", adminPanel: "Admin Panel",
    welcome: "Welcome", login: "Login", logout: "Logout",
    approve: "Approve", reject: "Reject", status: "Status",
    pending: "Pending", approved: "Approved",
    userMgmt: "User Access", searchPlaceholder: "Ask anything about your documents...",
    brandName: "DocuMind", portalName: "Intel Portal",
    history: "History", download: "Download", delete: "Delete",
    createFolder: "New Folder", uploadFile: "Upload File",
    back: "Back", emptyFolder: "This folder is empty",
    folderNamePlaceholder: "Enter folder name...",
    startNew: "Start New", recentDiscussions: "Recent",
    knowledgeTitle: "Knowledge Base", uploadDesc: "Upload",
    noDocsFocused: "No documents selected for this session", docDetails: "Details",
    restore: "Restore", modeLibrary: "Global Library", modeFocus: "Session Files",
    selectMode: "Mode", focusNewDocs: "Upload Files",
    focusDesc: "Chat with specific documents",
    useLibrary: "Library", libraryDesc: "Search all approved data",
    summaryPrompt: "Summarize the key findings.",
    rawContent: "Source Content", focusedDocs: "Context Files",
    uploadSuccess: "Uploaded!",
    folderSuccess: "Folder created!",
    activityTitle: "Activity Log", selectFolderChat: "Context:",
    allFolders: "Full Library",
    slogan: "Your Knowledge, Amplified by Intelligence.",
    uploading: "Processing files...",
    selectToChat: "Select files to include in conversation"
  },
  Vietnamese: {
    langCode: "VN", home: "Trang chủ", research: "Nghiên cứu", library: "Thư viện",
    folderMgmt: "Thư mục", trash: "Thùng rác", adminPanel: "Quản trị",
    welcome: "Chào mừng", login: "Đăng nhập", logout: "Đăng xuất",
    approve: "Duyệt", reject: "Từ chối", status: "Trạng thái",
    pending: "Chờ duyệt", approved: "Đã duyệt",
    userMgmt: "Phân quyền User", searchPlaceholder: "Hỏi bất cứ điều gì về tài liệu của bạn...",
    brandName: "DocuMind", portalName: "Cổng thông tin",
    history: "Lịch sử", download: "Tải về", delete: "Xóa",
    createFolder: "Thư mục mới", uploadFile: "Tải file lên",
    back: "Quay lại", emptyFolder: "Thư mục này trống",
    folderNamePlaceholder: "Nhập tên thư mục...",
    startNew: "Bắt đầu mới", recentDiscussions: "Thảo luận gần đây",
    knowledgeTitle: "Kho tri thức", uploadDesc: "Tải lên",
    noDocsFocused: "Chưa có tài liệu nào được chọn cho phiên này", docDetails: "Chi tiết tài liệu",
    restore: "Khôi phục", modeLibrary: "Thư viện chung", modeFocus: "Tệp tải lên",
    selectMode: "Chế độ", focusNewDocs: "Tải tệp lên",
    focusDesc: "Trò chuyện với tài liệu cụ thể",
    useLibrary: "Dùng thư viện", libraryDesc: "Tìm kiếm toàn bộ kho",
    summaryPrompt: "Tóm tắt các ý chính.",
    rawContent: "Nội dung gốc", focusedDocs: "Tệp ngữ cảnh",
    uploadSuccess: "Đã tải lên!",
    folderSuccess: "Đã tạo thư mục!",
    activityTitle: "Lịch sử hoạt động", selectFolderChat: "Ngữ cảnh:",
    allFolders: "Toàn bộ thư viện",
    slogan: "Tri thức của bạn, Sức mạnh của chúng tôi.",
    uploading: "Đang xử lý tài liệu...",
    selectToChat: "Chọn tài liệu để bắt đầu trò chuyện"
  },
  French: { langCode: "FR", slogan: "Votre savoir, amplifié.", allFolders: "Bibliothèque", selectFolderChat: "Contexte:", research: "Recherche", modeLibrary: "Bibliothèque", modeFocus: "Fichiers" },
  German: { langCode: "DE", slogan: "Ihr Wissen, intelligent erweitert.", allFolders: "Bibliothek", selectFolderChat: "Kontext:", research: "Forschung", modeLibrary: "Bibliothek", modeFocus: "Dateien" },
  Japanese: { langCode: "JP", slogan: "あなたの知識を、知能で強化する。", allFolders: "全ライブラリ", selectFolderChat: "コンテキスト:", research: "研究", modeLibrary: "ライブラリ", modeFocus: "ファイル" },
  Korean: { langCode: "KR", slogan: "당신의 지식, 지능으로 증폭되다.", allFolders: "전체 라이브러리", selectFolderChat: "컨텍스트:", research: "연구", modeLibrary: "라이브러리", modeFocus: "파일" },
  Chinese: { langCode: "CN", slogan: "您的知识，由智能赋能。", allFolders: "完整库", selectFolderChat: "背景:", research: "研究", modeLibrary: "图书馆", modeFocus: "文件" }
};
