
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  English: {
    langCode: "EN", home: "Home", research: "Research", library: "Library",
    welcome: "Intelligence Hub", selectLang: "Language", docsSelected: "selected",
    trendingTitle: "Global Trends", knowledgeTitle: "Knowledge Base",
    uploadDesc: "Upload docs", startNew: "New Research",
    recentDiscussions: "Recent Discussions", noHistory: "No history yet",
    backToHome: "Back to Home", loading: "AI is thinking...",
    searchPlaceholder: "Ask anything about your knowledge...",
    globalSearch: "Global Mode", sessionStarted: "Session started",
    updateNews: "Update", docDetails: "Document Details",
    focusNewDocs: "Research New Docs", useLibrary: "Use Knowledge Base",
    focusDesc: "Upload specific files to focus your research session.",
    libraryDesc: "Analyze and query from your existing document library.",
    uploadAndStart: "Upload & Start",
    selectMode: "Research Configuration",
    focusedDocs: "Focused Documents",
    noDocsFocused: "No documents focused yet.",
    tagline: "Unify your knowledge library and global trends.",
    brandName: "DocuMind",
    portalName: "GenAI Research Portal",
    newSession: "NEW SESSION",
    modeLibrary: "LIBRARY",
    modeFocus: "FOCUS FILES",
    summaryPrompt: "Summarize my current knowledge base.",
    rawContent: "RAW CONTENT",
    poweredBy: "Intelligence Powered by Gemini 3.0"
  },
  Vietnamese: {
    langCode: "VN", home: "Trang chủ", research: "Nghiên cứu", library: "Thư viện",
    welcome: "Trung tâm Trí tuệ", selectLang: "Ngôn ngữ", docsSelected: "đã chọn",
    trendingTitle: "Xu hướng thế giới", knowledgeTitle: "Kho kiến thức",
    uploadDesc: "Tải lên tài liệu", startNew: "Nghiên cứu mới",
    recentDiscussions: "Thảo luận gần đây", noHistory: "Chưa có lịch sử thảo luận",
    backToHome: "Quay lại trang chủ", loading: "AI đang suy nghĩ...",
    searchPlaceholder: "Hỏi bất cứ điều gì về kiến thức của bạn...",
    globalSearch: "Chế độ Toàn cầu", sessionStarted: "Phiên đã bắt đầu",
    updateNews: "Cập nhật", docDetails: "Chi tiết tài liệu",
    focusNewDocs: "Tập trung Tài liệu mới", useLibrary: "Dùng Kho kiến thức tổng quát",
    focusDesc: "Tải lên file cụ thể để AI chỉ tập trung trả lời dựa trên chúng.",
    libraryDesc: "AI sẽ sử dụng toàn bộ dữ liệu bạn đã nạp vào thư viện.",
    uploadAndStart: "Tải lên & Bắt đầu",
    selectMode: "Cấu hình Nghiên cứu",
    focusedDocs: "Tài liệu đang tập trung",
    noDocsFocused: "Chưa có tài liệu nào được tải lên.",
    tagline: "Hợp nhất thư viện kiến thức và xu hướng toàn cầu.",
    brandName: "DocuMind",
    portalName: "Cổng nghiên cứu GenAI",
    newSession: "PHIÊN MỚI",
    modeLibrary: "THƯ VIỆN",
    modeFocus: "TẬP TRUNG FILE",
    summaryPrompt: "Hãy tóm tắt kho kiến thức hiện tại của tôi.",
    rawContent: "DỮ LIỆU GỐC",
    poweredBy: "Trí tuệ nhân tạo được cung cấp bởi Gemini 3.0"
  },
  French: { langCode: "FR", home: "Accueil", research: "Recherche", welcome: "Centre d'Intelligence", trendingTitle: "Tendances", knowledgeTitle: "Savoir", uploadDesc: "Déposer", startNew: "Nouvelle Recherche", recentDiscussions: "Discussions récentes", focusNewDocs: "Nouveaux Docs", useLibrary: "Base de Connaissances", tagline: "Unifiez votre bibliothèque.", brandName: "DocuMind", portalName: "Portail GenAI", newSession: "NOUVEAU", modeLibrary: "BIBLIO", modeFocus: "FOCUS", summaryPrompt: "Résumez mes connaissances.", rawContent: "CONTENU BRUT", poweredBy: "Propulsé par Gemini 3.0" },
  German: { langCode: "DE", home: "Home", research: "Forschung", welcome: "Wissenszentrum", trendingTitle: "Trends", knowledgeTitle: "Wissen", uploadDesc: "Hochladen", startNew: "Neue Forschung", recentDiscussions: "Letzte Diskussionen", focusNewDocs: "Neue Dok", useLibrary: "Wissensdatenbank", tagline: "Wissen vereinheitlichen.", brandName: "DocuMind", portalName: "GenAI Portal", newSession: "NEU", modeLibrary: "BIBLIOTHEK", modeFocus: "FOKUS", summaryPrompt: "Fasse mein Wissen zusammen.", rawContent: "ROHDATEN", poweredBy: "Unterstützt durch Gemini 3.0" },
  Japanese: { langCode: "JP", home: "ホーム", research: "研究", welcome: "ナレッジセンター", trendingTitle: "トレンド", knowledgeTitle: "知識", uploadDesc: "アップロード", startNew: "新規研究", recentDiscussions: "最近の議論", focusNewDocs: "新規ドキュメント", useLibrary: "ナレッジベース", tagline: "知識とトレンドの統合。", brandName: "DocuMind", portalName: "GenAI ポータル", newSession: "新規", modeLibrary: "ライブラリ", modeFocus: "フォーカス", summaryPrompt: "知識を要約して。", rawContent: "生データ", poweredBy: "Gemini 3.0 による知能" },
  Korean: { langCode: "KR", home: "홈", research: "연구", welcome: "지식 센터", trendingTitle: "트렌드", knowledgeTitle: "지식", uploadDesc: "업로드", startNew: "새 연구", recentDiscussions: "최근 토론", focusNewDocs: "새 문서", useLibrary: "지식 베이스", tagline: "지식과 트렌드 통합.", brandName: "DocuMind", portalName: "GenAI 포털", newSession: "신규", modeLibrary: "라이브러리", modeFocus: "포커스", summaryPrompt: "지식 요약해줘.", rawContent: "원본 데이터", poweredBy: "Gemini 3.0 기반 인공지능" },
  Chinese: { langCode: "CN", home: "首页", research: "研究", welcome: "知识中心", trendingTitle: "热门", knowledgeTitle: "知识库", uploadDesc: "上传", startNew: "新研究", recentDiscussions: "最近讨论", focusNewDocs: "新文档", useLibrary: "知识库", tagline: "统一您的知识库。", brandName: "DocuMind", portalName: "GenAI 门户", newSession: "新建", modeLibrary: "资料库", modeFocus: "专注", summaryPrompt: "总结我的知识库。", rawContent: "原始内容", poweredBy: "由 Gemini 3.0 提供动力" }
};
